project_id = "qcjgtysctnvkjpbfxoqm"

[functions.auth-telegram]
verify_jwt = false

[functions.upload-file]
verify_jwt = false

[functions.sync-sheets]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.personal-task-reminder]
verify_jwt = false
